/**
 * AstroGuard Bio-Link Gateway Service
 * 
 * Hardware-ready Device Adapter & Telemetry Bridge Interface.
 * Manages physical/simulated device connectivity, pairing, buffering, and telemetry normalization.
 */

export type DeviceCategory =
  | "bio_patch"
  | "smartwatch"
  | "cgm"
  | "bp_monitor"
  | "pulse_oximeter"
  | "rfid_scanner"
  | "other";

export type ConnectionProtocol = "BLE 5.3" | "USB 3.0 / Serial" | "Local Wi-Fi 6" | "Gateway Direct";
export type DeviceConnectionState = "connected" | "offline" | "unstable" | "stale" | "buffering";
export type SignalQuality = "excellent" | "good" | "weak" | "offline";

export interface IBioLinkDevice {
  deviceId: string;
  astronautId: string;
  deviceType: DeviceCategory;
  name: string;
  manufacturer: string;
  model: string;
  firmwareVersion: string;
  connectionType: ConnectionProtocol;
  status: DeviceConnectionState;
  batteryLevel: number;
  signalStrength: SignalQuality;
  rssiDbm: number;
  lastSeen: string;
  pairedAt: string;
  isSimulated: boolean;
  calibrationStatus: string;
  assignedSensors: string[];
  lastMeasurementValue?: string;
  dataNature: "Direct Sensor" | "Derived / Algorithmic" | "RFID Ingestion" | "AI Diagnostics";
}

export interface IGatewayMetadata {
  gatewayId: string;
  name: string;
  location: string;
  status: "CONNECTED" | "BUFFERING" | "OFFLINE";
  encryption: string;
  firmware: string;
  dataStream: string;
  activeDevices: number;
  lastSync: string;
  networkMode: string;
  bufferedPackets: number;
  bufferCapacityPackets: number;
}

export interface ISensorMappingEntry {
  parameter: string;
  sensor: string;
  device: string;
  connection: ConnectionProtocol;
  gateway: string;
  backendService: string;
  dashboardComponent: string;
  dataNature: "Direct Sensor" | "Derived / Algorithmic" | "RFID Ingestion" | "Specialized Device" | "AI Diagnostics";
  scientificRationale: string;
}

/**
 * Sensor-to-Dashboard Technical Architecture Mapping Matrix
 */
export const SENSOR_TECHNICAL_MAPPING: ISensorMappingEntry[] = [
  {
    parameter: "Heart Rate (BPM)",
    sensor: "Multi-wavelength Optical PPG & 2-Lead ECG",
    device: "Bio-Patch Pro X4 (BP-AST001-01)",
    connection: "BLE 5.3",
    gateway: "Bio-Link BLG-001",
    backendService: "TelemetryService (100Hz Ingest)",
    dashboardComponent: "Biometric Vitals Stream + Live ECG Lead II",
    dataNature: "Direct Sensor",
    scientificRationale: "Reflectance photoplethysmography measures capillary blood volume pulse at 530nm/660nm.",
  },
  {
    parameter: "Blood Pressure (mmHg)",
    sensor: "Pneumatic Oscillometric Pressure Transducer",
    device: "Hemodynamic BP Cuff (BPM-AST001-01)",
    connection: "BLE 5.3",
    gateway: "Bio-Link BLG-001",
    backendService: "HealthData Ingestion API",
    dashboardComponent: "Cardiac Organ Telemetry & Vitals Card",
    dataNature: "Specialized Device",
    scientificRationale: "Validated oscillometric cuff detects mean arterial pressure pulse envelope oscillations.",
  },
  {
    parameter: "SpO₂ Saturation (%)",
    sensor: "Dual-Wavelength Red (660nm) & IR (940nm) Oximeter",
    device: "Bio-Patch Pro X4 / Pulse Oximeter",
    connection: "BLE 5.3",
    gateway: "Bio-Link BLG-001",
    backendService: "TelemetryService",
    dashboardComponent: "Respiratory Organ Telemetry & Vitals Card",
    dataNature: "Direct Sensor",
    scientificRationale: "Differential absorption of oxygenated vs deoxygenated hemoglobin gives arterial oxygen saturation.",
  },
  {
    parameter: "Interstitial Glucose (mg/dL)",
    sensor: "Subcutaneous Glucose-Oxidase Enzymatic Electrode",
    device: "GlycoSense Micro-Probe CGM (CGM-AST001-01)",
    connection: "BLE 5.3",
    gateway: "Bio-Link BLG-001",
    backendService: "TelemetryService & Metabolic Engine",
    dashboardComponent: "24h Timeline Chart + Metabolic HUD",
    dataNature: "Direct Sensor",
    scientificRationale: "Amperometric current generated by catalytic oxidation of interstitial fluid glucose.",
  },
  {
    parameter: "Body Temperature (°C)",
    sensor: "High-Precision Negative Temp Coefficient (NTC) Thermistor",
    device: "Bio-Patch Pro X4 (BP-AST001-01)",
    connection: "BLE 5.3",
    gateway: "Bio-Link BLG-001",
    backendService: "TelemetryService",
    dashboardComponent: "Biometric Vitals Stream & Cockpit Matrix",
    dataNature: "Direct Sensor",
    scientificRationale: "Continuous skin thermometry compensated with ambient microclimate thermal flux model.",
  },
  {
    parameter: "Sleep & Rest Quality",
    sensor: "3-Axis Actigraphy + Heart Rate Variability (HRV)",
    device: "Tactical Smartwatch (SW-AST001-01)",
    connection: "BLE 5.3",
    gateway: "Bio-Link BLG-001",
    backendService: "Circadian Rhythm Analysis Engine",
    dashboardComponent: "Neuro/Sleep Organ Telemetry & Readiness Gauge",
    dataNature: "Derived / Algorithmic",
    scientificRationale: "Calculated via polysomnography-trained deep learning algorithm on IMU motion + HRV power spectral density.",
  },
  {
    parameter: "Physical Activity & Steps",
    sensor: "6-Axis Inertial Measurement Unit (IMU: Accel + Gyro)",
    device: "Tactical Smartwatch (SW-AST001-01)",
    connection: "BLE 5.3",
    gateway: "Bio-Link BLG-001",
    backendService: "Biomechanics & Activity Service",
    dashboardComponent: "Activity & Caloric Burn Card",
    dataNature: "Derived / Algorithmic",
    scientificRationale: "Microgravity step equivalents calculated via zero-g resistive exercise harness motion signatures.",
  },
  {
    parameter: "Weight & BMI (kg, kg/m²)",
    sensor: "Load Cell Strain Gauge or BIA Impedance Scale",
    device: "Body Mass Measurement Device (BMMD)",
    connection: "BLE 5.3",
    gateway: "Bio-Link BLG-001",
    backendService: "Physical Fitness Records",
    dashboardComponent: "Weight & BMI Vitals Card",
    dataNature: "Specialized Device",
    scientificRationale: "In zero-g, mass is measured using linear acceleration harmonic oscillation (F = ma) or manual scale entry.",
  },
  {
    parameter: "Space-Meal Nutrition & RFID",
    sensor: "13.56 MHz High-Frequency RFID Interrogator (ISO 14443)",
    device: "Hab-Station RFID Meal Reader (RFID-AST001-01)",
    connection: "USB 3.0 / Serial",
    gateway: "Bio-Link BLG-001",
    backendService: "NutritionService & Micronutrient Assay",
    dashboardComponent: "Nutrient Radar + Macro HUD + Micro-Array Assay",
    dataNature: "RFID Ingestion",
    scientificRationale: "Passive RFID tag on space meal pouch transmits encrypted barcode linking to laboratory nutritional mass spectrometer data.",
  },
  {
    parameter: "AI Care Guidance & Recommendations",
    sensor: "Multi-modal Real-time Telemetry Analytics Engine",
    device: "AstroGuard Neural Health Engine",
    connection: "Gateway Direct",
    gateway: "Bio-Link BLG-001",
    backendService: "AI Medical Diagnostics & Guidance Service",
    dashboardComponent: "AI Care Recommendation Banner & Organ Status",
    dataNature: "AI Diagnostics",
    scientificRationale: "Autonomous inference comparing longitudinal astronaut baseline with real-time biometric and nutritional streams.",
  },
];

/**
 * Standard Simulated Astronaut Devices Initial Registry
 */
export const DEFAULT_DEVICE_CATALOG: IBioLinkDevice[] = [
  {
    deviceId: "BP-AST001-01",
    astronautId: "AST-001",
    deviceType: "bio_patch",
    name: "Medical Bio-Patch Pro X4",
    manufacturer: "AstroGuard BioMed Systems",
    model: "BioPatch-Pro X4",
    firmwareVersion: "v3.1.2-space-rtos",
    connectionType: "BLE 5.3",
    status: "connected",
    batteryLevel: 87,
    signalStrength: "excellent",
    rssiDbm: -52,
    lastSeen: "Just now",
    pairedAt: "2026-09-15T08:00:00Z",
    isSimulated: true,
    calibrationStatus: "Lead-II ECG Calibrated · Zero-G Certified",
    assignedSensors: ["Optical PPG (Heart Rate)", "SpO2 Dual-Wavelength", "NTC Core Thermistor", "Skin Impedance"],
    lastMeasurementValue: "76 BPM · 98% SpO₂ · 36.8°C",
    dataNature: "Direct Sensor",
  },
  {
    deviceId: "SW-AST001-01",
    astronautId: "AST-001",
    deviceType: "smartwatch",
    name: "Astronaut Tactical Smartwatch",
    manufacturer: "Orbital Dynamics Wearables",
    model: "AstroWatch Space-Edition",
    firmwareVersion: "v2.8.4",
    connectionType: "BLE 5.3",
    status: "connected",
    batteryLevel: 72,
    signalStrength: "good",
    rssiDbm: -64,
    lastSeen: "3 sec ago",
    pairedAt: "2026-09-12T14:30:00Z",
    isSimulated: true,
    calibrationStatus: "6-Axis IMU Actigraphy Calibrated",
    assignedSensors: ["6-Axis Accelerometer/Gyroscope", "Wrist PPG Sensor", "Barometric Altimeter"],
    lastMeasurementValue: "8,420 steps · 485 kcal · Sleep 7.6h",
    dataNature: "Derived / Algorithmic",
  },
  {
    deviceId: "CGM-AST001-01",
    astronautId: "AST-001",
    deviceType: "cgm",
    name: "Continuous Glucose Monitor",
    manufacturer: "EndoSpace Therapeutics",
    model: "GlycoSense Micro-Probe",
    firmwareVersion: "v1.9.0",
    connectionType: "BLE 5.3",
    status: "connected",
    batteryLevel: 91,
    signalStrength: "excellent",
    rssiDbm: -49,
    lastSeen: "4 sec ago",
    pairedAt: "2026-10-01T06:15:00Z",
    isSimulated: true,
    calibrationStatus: "Enzymatic Glucose Sensor Validated",
    assignedSensors: ["Subcutaneous Enzymatic Interstitial Glucose Sensor"],
    lastMeasurementValue: "94 mg/dL (Nominal Postprandial)",
    dataNature: "Direct Sensor",
  },
  {
    deviceId: "BPM-AST001-01",
    astronautId: "AST-001",
    deviceType: "bp_monitor",
    name: "Digital Hemodynamic BP Cuff",
    manufacturer: "AeroHealth MedTech",
    model: "PressuGrip-ZeroG",
    firmwareVersion: "v2.1.0",
    connectionType: "BLE 5.3",
    status: "connected",
    batteryLevel: 68,
    signalStrength: "good",
    rssiDbm: -68,
    lastSeen: "12 min ago",
    pairedAt: "2026-09-20T11:00:00Z",
    isSimulated: true,
    calibrationStatus: "Oscillometric Transducer Verified",
    assignedSensors: ["Pneumatic Oscillometric Pressure Transducer"],
    lastMeasurementValue: "118 / 78 mmHg (Resting)",
    dataNature: "Direct Sensor",
  },
  {
    deviceId: "RFID-AST001-01",
    astronautId: "AST-001",
    deviceType: "rfid_scanner",
    name: "Hab-Station RFID Meal Reader",
    manufacturer: "ISS Habitation Systems",
    model: "NutriScan 13.56MHz HF",
    firmwareVersion: "v4.0.1-embedded",
    connectionType: "USB 3.0 / Serial",
    status: "connected",
    batteryLevel: 100,
    signalStrength: "excellent",
    rssiDbm: -30,
    lastSeen: "Just now",
    pairedAt: "2026-09-01T00:00:00Z",
    isSimulated: true,
    calibrationStatus: "ISO/IEC 14443 Type A Certified",
    assignedSensors: ["13.56MHz High-Frequency RFID / NFC Interrogator"],
    lastMeasurementValue: "Pack Ingested: RFID-HMP-001",
    dataNature: "RFID Ingestion",
  },
];
