"use client";

import Image from "next/image";
import Link from "next/link";
import { useAuth } from "../../../context/AuthContext";
import { Activity, BadgeCheck, Bell, BriefcaseMedical, CheckCircle2, ChevronRight, Globe2, KeyRound, Mail, MapPin, Phone, ShieldCheck, Stethoscope, UserRound } from "lucide-react";

export default function MedicalProfilePage() {
  const { user, logout } = useAuth();
  const name = user?.name || "Dr. Sarah Wilson";
  const email = user?.email || "medical@astroguard.local";
  return <div className="space-y-6"><header className="flex flex-col justify-between gap-4 border-b border-cyan-400/15 pb-5 sm:flex-row sm:items-end"><div><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.2em] text-cyan-300"><Stethoscope className="h-4 w-4" /> Medical Officer Identity</div><h1 className="mt-2 text-3xl font-black tracking-tight text-white">Doctor Profile</h1><p className="mt-1 text-sm text-slate-400">Manage your clinical identity, operational clearance, and mission access.</p></div><span className="inline-flex items-center gap-2 self-start rounded-full border border-emerald-400/25 bg-emerald-500/10 px-3 py-2 text-xs font-bold text-emerald-300"><span className="h-2 w-2 rounded-full bg-emerald-400" /> Secure session active</span></header>
    <div className="grid gap-5 xl:grid-cols-[0.8fr_1.2fr]"><section className="relative overflow-hidden rounded-3xl border border-cyan-400/25 bg-gradient-to-br from-[#0a2a55] via-[#061735] to-[#041024] p-6"><div className="absolute -right-16 -top-16 h-48 w-48 rounded-full bg-cyan-400/10 blur-3xl" /><div className="relative flex flex-col items-center text-center"><div className="relative h-32 w-32 overflow-hidden rounded-full border-2 border-cyan-300/70 bg-cyan-500/10 shadow-[0_0_35px_rgba(34,211,238,0.2)]"><Image src="/astronaut-avatar.png" alt={name} fill className="object-cover" /></div><span className="mt-4 inline-flex items-center gap-1.5 rounded-full border border-emerald-400/25 bg-emerald-400/10 px-3 py-1 text-[10px] font-bold text-emerald-300"><BadgeCheck className="h-3.5 w-3.5" /> VERIFIED MEDICAL OFFICER</span><h2 className="mt-3 text-2xl font-black text-white">{name}</h2><p className="mt-1 text-sm font-semibold text-cyan-200">Flight Surgeon · MED-002</p><p className="mt-1 font-mono text-[10px] text-slate-500">Ares Mission 01 · Medical Operations Center</p></div><div className="relative mt-6 grid grid-cols-3 gap-2 border-t border-white/10 pt-5 text-center"><div><p className="text-xl font-black text-white">{user?.assignedAstronautIds?.length || 6}</p><p className="text-[10px] text-slate-500">Crew monitored</p></div><div><p className="text-xl font-black text-cyan-200">24/7</p><p className="text-[10px] text-slate-500">Coverage</p></div><div><p className="text-xl font-black text-emerald-300">Active</p><p className="text-[10px] text-slate-500">Clearance</p></div></div></section>
      <section className="rounded-3xl border border-cyan-400/20 bg-[#061735]/80 p-5"><div className="flex items-center justify-between border-b border-sky-400/10 pb-4"><div><h2 className="text-base font-bold text-white">Professional Identity</h2><p className="mt-1 text-xs text-slate-500">Authenticated account information</p></div><ShieldCheck className="h-5 w-5 text-cyan-300" /></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><Info icon={Mail} label="Secure email" value={email} /><Info icon={BriefcaseMedical} label="Role" value="Medical Officer / Flight Surgeon" /><Info icon={KeyRound} label="Medical ID" value="MED-002" /><Info icon={Globe2} label="Mission" value="Ares Mission 01" /><Info icon={Phone} label="Emergency channel" value="Mission Control · Channel 03" /><Info icon={MapPin} label="Duty station" value="Orbital Medical Operations" /></div></section></div>
    <div className="grid gap-5 lg:grid-cols-3"><section className="rounded-2xl border border-cyan-400/20 bg-[#061735]/80 p-5 lg:col-span-2"><div className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-cyan-300" /><h2 className="text-base font-bold text-white">Operational Clearance</h2></div><p className="mt-1 text-xs text-slate-500">Permissions available to this Medical Officer session.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><Clearance title="Crew health monitoring" detail="View astronaut telemetry and clinical signals" /><Clearance title="Clinical instructions" detail="Issue documented countermeasures to astronauts" /><Clearance title="Authority escalation" detail="Forward critical cases to Mission Authority" /></div></section><section className="rounded-2xl border border-cyan-400/20 bg-[#061735]/80 p-5"><h2 className="text-base font-bold text-white">Quick Access</h2><div className="mt-4 space-y-2"><Quick href="/medical/clinical-protocols" icon={Activity} label="Health Monitoring" /><Quick href="/medical/alerts" icon={Bell} label="Medical Alerts" /><Quick href="/medical/dashboard" icon={UserRound} label="Crew Overview" /></div></section></div>
    <section className="flex flex-col justify-between gap-4 rounded-2xl border border-rose-400/20 bg-rose-500/5 p-5 sm:flex-row sm:items-center"><div><div className="flex items-center gap-2 text-sm font-bold text-rose-200"><KeyRound className="h-4 w-4" /> Secure Session Controls</div><p className="mt-1 text-xs text-slate-500">Sign out when leaving the Medical Operations Center.</p></div><button onClick={() => void logout()} className="inline-flex items-center justify-center gap-2 rounded-xl border border-rose-400/25 bg-rose-500/10 px-4 py-2.5 text-xs font-bold text-rose-200 hover:bg-rose-500/20">Sign out securely <ChevronRight className="h-3.5 w-3.5" /></button></section>
  </div>;
}

function Info({ icon: Icon, label, value }: { icon: typeof Mail; label: string; value: string }) { return <div className="rounded-xl border border-white/10 bg-black/20 p-3"><div className="flex items-center gap-2 text-[10px] uppercase tracking-wider text-slate-500"><Icon className="h-3.5 w-3.5 text-cyan-300" /> {label}</div><p className="mt-2 truncate text-xs font-semibold text-white">{value}</p></div>; }
function Clearance({ title, detail }: { title: string; detail: string }) { return <div className="flex gap-3 rounded-xl border border-emerald-400/15 bg-emerald-500/5 p-3"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-emerald-300" /><div><p className="text-xs font-bold text-white">{title}</p><p className="mt-1 text-[10px] text-slate-500">{detail}</p></div></div>; }
function Quick({ href, icon: Icon, label }: { href: string; icon: typeof Activity; label: string }) { return <Link href={href} className="flex items-center gap-3 rounded-xl border border-sky-400/10 bg-blue-500/10 px-3 py-2.5 text-xs font-semibold text-slate-200 hover:bg-blue-500/20"><Icon className="h-4 w-4 text-cyan-300" /><span className="flex-1">{label}</span><ChevronRight className="h-3.5 w-3.5 text-cyan-300" /></Link>; }
