import { Request, Response, NextFunction } from "express";
import { AlertService } from "../services/alert.service.js";
import { successResponse, errorResponse } from "../utils/response.js";

export class AlertController {
  public static async getAlerts(req: Request, res: Response, next: NextFunction) { try {
    const severity = req.query.severity as string | undefined; const resolved = req.query.resolved !== undefined ? req.query.resolved === "true" : undefined; const limit = req.query.limit ? parseInt(req.query.limit as string, 10) : 50; const user = req.user; const alerts = await AlertService.getAlerts({ severity, resolved, limit });
    const filteredAlerts = alerts.filter((a) => { if (user?.role === "astronaut") return a.astronautId === user.astronautId; if (user?.role === "medical_officer" && user.assignedAstronautIds?.length && req.query.scope !== "all") return user.assignedAstronautIds.includes(a.astronautId); return true; }); return successResponse(res, filteredAlerts, 200);
  } catch (error) { next(error); } }
  public static async getAstronautAlerts(req: Request, res: Response, next: NextFunction) { try { const alerts = await AlertService.getAlertsByAstronaut(req.params.astronautId); return successResponse(res, alerts, 200); } catch (error) { next(error); } }
  public static async createEmergency(req: Request, res: Response, next: NextFunction) { try { const user = req.user!; if (user.role !== "astronaut" || !user.astronautId) return errorResponse(res, "Only an authenticated astronaut can trigger Emergency SOS.", 403); const reason = String(req.body?.reason || "Unspecified emergency"); const allowed = ["Extreme Dizziness", "Acute Pain", "Breathing Issue", "Disorientation"]; if (!allowed.includes(reason)) return errorResponse(res, "Unsupported emergency reason.", 400); const alert = await AlertService.createAlert({ astronautId: user.astronautId, title: `EMERGENCY SOS — ${reason}`, description: `Critical emergency signal initiated by ${user.name}. Immediate medical and mission-control review required.`, severity: "Critical", signal: "EMERGENCY_SOS", value: reason, baseline: "N/A" }); return successResponse(res, alert, 201, "Emergency SOS transmitted to Medical Operations and Mission Control."); } catch (error) { next(error); } }
  public static async resolveAlert(req: Request, res: Response, next: NextFunction) { try { const alert = await AlertService.resolveAlert(req.params.id); if (!alert) return errorResponse(res, `Alert not found with ID: ${req.params.id}`, 404); return successResponse(res, alert, 200, "Alert marked as resolved"); } catch (error) { next(error); } }
}
