import { Request, Response, NextFunction } from "express";
import { DiagnosticOrder, CountermeasureExecution } from "../models/ClinicalOperations.js";
import { canAccessRawMedicalData, isAssignedMedicalOfficer } from "../services/medicalAccess.service.js";
import { successResponse, errorResponse } from "../utils/response.js";

const types = ["URINALYSIS", "ULTRASOUND", "VENOUS_BLOOD_DRAW", "ECG", "VISION_CHECK"];
const protocols = ["LBNP", "CEVIS", "ELECTROLYTE_REHYDRATION", "VITAMIN_D", "BISPHOSPHONATE"];
export class ClinicalOperationsController {
  static async listOrders(req: Request, res: Response, next: NextFunction) { try { const astronautId = String(req.query.astronautId || req.user!.astronautId || ""); if (!astronautId || !(await canAccessRawMedicalData(req.user!, astronautId))) return errorResponse(res, "Clinical order access denied.", 403); return successResponse(res, { orders: await DiagnosticOrder.find({ astronautId }).sort({ createdAt: -1 }).limit(100) }, 200); } catch (error) { next(error); } }
  static async createOrder(req: Request, res: Response, next: NextFunction) { try { if (req.user!.role !== "medical_officer") return errorResponse(res, "Only a Flight Surgeon can order diagnostics.", 403); const { astronautId, type, priority = "ROUTINE", instructions } = req.body || {}; if (!astronautId || !types.includes(type) || !instructions) return errorResponse(res, "Astronaut, diagnostic type, and instructions are required.", 400); if (!(await isAssignedMedicalOfficer(req.user!, astronautId))) return errorResponse(res, "Astronaut is not assigned to this Flight Surgeon.", 403); const order = await DiagnosticOrder.create({ astronautId, orderedBy: req.user!._id.toString(), type, priority, instructions }); return successResponse(res, order, 201, "Diagnostic order transmitted to onboard station."); } catch (error) { next(error); } }
  static async updateOrder(req: Request, res: Response, next: NextFunction) { try { const order = await DiagnosticOrder.findById(req.params.id); if (!order || !(await canAccessRawMedicalData(req.user!, order.astronautId))) return errorResponse(res, "Diagnostic order access denied.", 403); order.status = req.body?.status || order.status; if (req.body?.result) order.result = req.body.result; await order.save(); return successResponse(res, order, 200, "Diagnostic order updated."); } catch (error) { next(error); } }
  static async listCountermeasures(req: Request, res: Response, next: NextFunction) { try { const astronautId = String(req.query.astronautId || req.user!.astronautId || ""); if (!astronautId || !(await canAccessRawMedicalData(req.user!, astronautId))) return errorResponse(res, "Countermeasure access denied.", 403); return successResponse(res, { countermeasures: await CountermeasureExecution.find({ astronautId }).sort({ createdAt: -1 }).limit(100) }, 200); } catch (error) { next(error); } }
  static async createCountermeasure(req: Request, res: Response, next: NextFunction) { try { if (req.user!.role !== "medical_officer") return errorResponse(res, "Only a Flight Surgeon can prescribe countermeasures.", 403); const { astronautId, protocol, parameters } = req.body || {}; if (!astronautId || !protocols.includes(protocol) || !parameters) return errorResponse(res, "Astronaut, protocol, and parameters are required.", 400); if (!(await isAssignedMedicalOfficer(req.user!, astronautId))) return errorResponse(res, "Astronaut is not assigned to this Flight Surgeon.", 403); return successResponse(res, await CountermeasureExecution.create({ astronautId, prescribedBy: req.user!._id.toString(), protocol, parameters }), 201, "Countermeasure protocol transmitted."); } catch (error) { next(error); } }
  static async updateCountermeasure(req: Request, res: Response, next: NextFunction) { try { const item = await CountermeasureExecution.findById(req.params.id); if (!item || !(await canAccessRawMedicalData(req.user!, item.astronautId))) return errorResponse(res, "Countermeasure access denied.", 403); item.status = req.body?.status || item.status; item.notes = req.body?.notes ?? item.notes; await item.save(); return successResponse(res, item, 200, "Countermeasure execution updated."); } catch (error) { next(error); } }
}
