import { Router } from "express";
import { AstronautController } from "../controllers/astronaut.controller.js";
import { BioSampleController } from "../controllers/bioSample.controller.js";
import { RecommendationController } from "../controllers/recommendation.controller.js";
import { validateRequest } from "../middleware/validation.middleware.js";
import { createAstronautSchema, getAstronautByIdSchema } from "../validators/astronaut.validator.js";
import { authenticate } from "../middleware/auth.middleware.js";
import { checkAstronautAccess } from "../middleware/ownership.middleware.js";
import { requireRole } from "../middleware/role.middleware.js";

const router = Router();
router.use(authenticate);
router.post("/me/bio-samples", requireRole("astronaut"), BioSampleController.create);
router.get("/me/bio-samples/latest", requireRole("astronaut"), BioSampleController.latest);
router.get("/me/bio-samples", requireRole("astronaut"), BioSampleController.history);
router.get("/me/recommendations", requireRole("astronaut"), RecommendationController.listByAstronaut);
router.patch("/me/recommendations/:id/read", requireRole("astronaut"), RecommendationController.markRead);
router.get("/", AstronautController.getAstronauts);
router.get("/:id", validateRequest(getAstronautByIdSchema), checkAstronautAccess("id"), AstronautController.getAstronautById);
router.post("/", requireRole("mission_control"), validateRequest(createAstronautSchema), AstronautController.createAstronaut);
router.put("/:id", requireRole("mission_control", "medical_officer"), validateRequest(getAstronautByIdSchema), checkAstronautAccess("id"), AstronautController.updateAstronaut);
router.delete("/:id", requireRole("mission_control"), validateRequest(getAstronautByIdSchema), AstronautController.deleteAstronaut);
export default router;
