import { Sparkles, BrainCircuit } from "lucide-react";
import { aiHealthInsight, baselineComparison } from "@/data/mockData";

export default function AIHealthInsight() {
  return (
    <section className="relative h-full overflow-hidden rounded-2xl border border-sky-400/20 bg-gradient-to-br from-[#0A2238] via-[#071A2E] to-[#0B2438] p-6 shadow-[0_10px_40px_rgba(0,0,0,0.35)]">
      {/* Decorative AI glow */}
      <div
        aria-hidden="true"
        className="pointer-events-none absolute -right-24 -top-24 h-64 w-64 rounded-full bg-[radial-gradient(circle,rgba(56,189,248,0.16),transparent_65%)] blur-2xl"
      />
      <div
        aria-hidden="true"
        className="pointer-events-none absolute -bottom-32 -right-16 h-56 w-56 rounded-full bg-[radial-gradient(circle,rgba(34,211,238,0.12),transparent_65%)] blur-2xl"
      />

      <div className="relative">
        <div className="flex items-start justify-between gap-3">
          <div className="flex items-center gap-2.5">
            <span className="flex h-9 w-9 items-center justify-center rounded-lg border border-primary/25 bg-primary/10 text-primary shadow-[0_0_18px_rgba(56,189,248,0.25)]">
              <Sparkles className="h-4 w-4" />
            </span>
            <div>
              <h2 className="text-sm font-semibold text-white">AI Health Insight</h2>
              <p className="mt-0.5 text-xs text-slate-400">Generated by AstroGuard AI engine</p>
            </div>
          </div>
          <span className="rounded-full border border-primary/25 bg-primary/10 px-2.5 py-0.5 text-[10px] font-bold tracking-wide text-primary">
            CONFIDENCE 94.2%
          </span>
        </div>

        <blockquote className="mt-5 border-l-2 border-primary/40 pl-4 text-sm leading-relaxed text-slate-200">
          &ldquo;{aiHealthInsight.summary}&rdquo;
        </blockquote>

        <div className="mt-6">
          <div className="flex items-center gap-2 text-[11px] font-bold uppercase tracking-[0.14em] text-slate-400">
            <BrainCircuit className="h-3.5 w-3.5 text-primary" />
            Baseline Comparison
          </div>
          <div className="mt-3 overflow-hidden rounded-xl border border-sky-400/10">
            <table className="w-full text-left text-xs">
              <thead>
                <tr className="border-b border-sky-400/10 bg-card-secondary/50 text-[10px] uppercase tracking-wider text-slate-500">
                  <th className="px-4 py-2.5 font-semibold">Signal</th>
                  <th className="px-4 py-2.5 font-semibold">Personal Baseline</th>
                  <th className="px-4 py-2.5 font-semibold">Mission Baseline</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-sky-400/[0.07]">
                {baselineComparison.map((row) => (
                  <tr key={row.label} className="transition-colors hover:bg-sky-500/[0.04]">
                    <td className="px-4 py-2.5 font-medium text-slate-200">{row.label}</td>
                    <td className="px-4 py-2.5 font-semibold text-white">{row.personal}</td>
                    <td className="px-4 py-2.5 text-slate-400">{row.mission}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        <p className="mt-5 flex items-center gap-2 text-[11px] text-slate-500">
          <BrainCircuit className="h-3.5 w-3.5 shrink-0 text-sky-400/70" />
          {aiHealthInsight.disclaimer}
        </p>
      </div>
    </section>
  );
}