import type { CrewMember } from "./api";

export const MOCK_CREW: CrewMember[] = [
  {
    userId: "660f1c3a9d1a4e0012ab1001",
    crewId: "AST-001",
    name: "Maya Chen",
    email: "maya.chen@astroguard.local",
    role: "astronaut",
    avatar: "MC",
    assigned: "EVA Space Walk & Solar Panel Maintenance",
    accountStatus: "Active",
    online: true,
    status: "On-Duty",
    missionIds: ["M-001"],
    assignedAstronautIds: [],
  },
  {
    userId: "660f1c3a9d1a4e0012ab1002",
    crewId: "AST-002",
    name: "Leo Park",
    email: "leo.park@astroguard.local",
    role: "astronaut",
    avatar: "LP",
    assigned: "EVA Space Walk & Solar Panel Maintenance",
    accountStatus: "Active",
    online: true,
    status: "On-Duty",
    missionIds: ["M-001"],
    assignedAstronautIds: [],
  },
  {
    userId: "660f1c3a9d1a4e0012ab1003",
    crewId: "AST-003",
    name: "Nina Volkov",
    email: "nina.volkov@astroguard.local",
    role: "astronaut",
    avatar: "NV",
    assigned: "Unassigned",
    accountStatus: "Banned",
    online: false,
    status: "Revoked",
    missionIds: [],
    assignedAstronautIds: [],
  },
  {
    userId: "660f1c3a9d1a4e0012ab1004",
    crewId: "AST-004",
    name: "Amara Okafor",
    email: "amara.okafor@astroguard.local",
    role: "astronaut",
    avatar: "AO",
    assigned: "Life Support Filter Replacement",
    accountStatus: "Active",
    online: true,
    status: "On-Duty",
    missionIds: ["M-003"],
    assignedAstronautIds: [],
  },
  {
    userId: "660f1c3a9d1a4e0012ab1005",
    crewId: "AST-005",
    name: "Diego Torres",
    email: "diego.torres@astroguard.local",
    role: "astronaut",
    avatar: "DT",
    assigned: "Orbital Navigation Calibration",
    accountStatus: "Active",
    online: false,
    status: "Off-Duty",
    missionIds: ["M-004"],
    assignedAstronautIds: [],
  },
  {
    userId: "660f1c3a9d1a4e0012ab2001",
    crewId: "MED-001",
    name: "Dr. Evelyn Reed",
    email: "evelyn.reed@astroguard.local",
    role: "medical_officer",
    avatar: "ER",
    assigned: "AST-001, AST-002",
    accountStatus: "Active",
    online: true,
    status: "On-Duty",
    missionIds: [],
    assignedAstronautIds: ["AST-001", "AST-002"],
  },
  {
    userId: "660f1c3a9d1a4e0012ab2002",
    crewId: "MED-002",
    name: "Dr. Marcus Chen",
    email: "marcus.chen@astroguard.local",
    role: "medical_officer",
    avatar: "MC",
    assigned: "AST-004",
    accountStatus: "Active",
    online: true,
    status: "On-Duty",
    missionIds: [],
    assignedAstronautIds: ["AST-004"],
  },
  {
    userId: "660f1c3a9d1a4e0012ab2003",
    crewId: "MED-003",
    name: "Dr. Sofia Marlowe",
    email: "sofia.marlowe@astroguard.local",
    role: "medical_officer",
    avatar: "SM",
    assigned: "No caseload",
    accountStatus: "Banned",
    online: false,
    status: "Revoked",
    missionIds: [],
    assignedAstronautIds: [],
  },
];